import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Brain, ShieldAlert } from "lucide-react";
import { AppShell } from "@/components/revive/shell";
import {
  Badge,
  ExecutionBadge,
  Metric,
  Panel,
  PolicyBadge,
  SeverityBadge,
  StatusBadge,
} from "@/components/revive/primitives";
import { SafetyPipeline } from "@/components/revive/pipeline";
import { Sparkline } from "@/components/revive/charts";
import { auditTrail, formatINR, formatTime, getIncident } from "@/lib/revive-data";

export const Route = createFileRoute("/incidents/$incidentId")({
  loader: ({ params }) => {
    const incident = getIncident(params.incidentId);
    if (!incident) throw notFound();
    return { incident };
  },
  head: ({ loaderData }) => {
    if (!loaderData) {
      return {
        meta: [{ title: "Incident not found — REVIVE AI" }, { name: "robots", content: "noindex" }],
      };
    }
    const { incident } = loaderData;
    const title = `${incident.id} · ${incident.title} — REVIVE AI`;
    const description = `${incident.severity} severity incident: ${incident.dropPct}% revenue drop, ${formatINR(incident.revenueAtRisk)} at risk. Root cause: ${incident.rootCause}.`;
    return {
      meta: [
        { title },
        { name: "description", content: description },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
      ],
    };
  },
  component: IncidentDetail,
});

function IncidentDetail() {
  const { incident } = Route.useLoaderData();
  const events = auditTrail
    .filter((e) => e.incidentId === incident.id)
    .sort((a, b) => (a.at < b.at ? -1 : 1));
  const blockedCount = incident.playbook.filter((a) => a.policyStatus === "blocked").length;
  const expected = incident.playbook.reduce((s, a) => s + a.expectedRecovery, 0);

  return (
    <AppShell title={`${incident.id} — Investigation`} subtitle={incident.title}>
      <Link
        to="/incidents"
        className="inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="size-3.5" /> Back to incidents
      </Link>

      <Panel className="mt-3">
        <div className="flex flex-wrap items-center gap-2">
          <SeverityBadge severity={incident.severity} />
          <StatusBadge status={incident.status} />
          <Badge tone="info">Confidence {incident.confidence}%</Badge>
          <span className="text-xs text-muted-foreground">
            Detected {formatTime(incident.detectedAt)} IST
          </span>
        </div>
        <h2 className="mt-3 text-lg font-semibold leading-snug">{incident.title}</h2>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <Metric label="Revenue drop" value={`${incident.dropPct}%`} tone="critical" />
          <Metric
            label="Revenue at risk"
            value={formatINR(incident.revenueAtRisk)}
            tone="critical"
          />
          <Metric
            label="Revenue recovered"
            value={formatINR(incident.revenueRecovered)}
            tone="success"
          />
          <Metric
            label="Affected transactions"
            value={incident.affectedTransactions.toLocaleString("en-IN")}
          />
        </div>
        <div className="mt-4">
          <SafetyPipeline
            blocked={blockedCount > 0}
            activeIndex={incident.status === "recovered" ? 5 : 4}
          />
        </div>
      </Panel>

      <div className="mt-4 grid gap-4 lg:grid-cols-3">
        <Panel title="Root cause" className="lg:col-span-1">
          <p className="text-sm leading-relaxed">{incident.rootCause}</p>
          <div className="mt-4">
            <p className="mb-1 text-[11px] uppercase tracking-wide text-muted-foreground">
              Success rate around the event
            </p>
            <Sparkline data={incident.sparkline} />
          </div>
        </Panel>

        <Panel title="AI diagnosis" className="lg:col-span-2">
          <div className="flex items-start gap-3 rounded-md border border-primary/25 bg-primary/8 p-3">
            <Brain className="mt-0.5 size-4 shrink-0 text-primary" />
            <p className="text-sm leading-relaxed">{incident.diagnosis}</p>
          </div>
          <p className="mt-3 text-[11px] text-muted-foreground">
            Generated by REVIVE diagnosis model · read-only analysis · no execution authority.
          </p>
        </Panel>
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <Panel title="Evidence">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-border text-[11px] uppercase tracking-wide text-muted-foreground">
                <th className="pb-2 font-medium">Signal</th>
                <th className="pb-2 font-medium">Observed</th>
                <th className="pb-2 font-medium">Baseline</th>
              </tr>
            </thead>
            <tbody>
              {incident.evidence.map((e) => (
                <tr key={e.signal} className="border-b border-border/60">
                  <td className="py-2 pr-3">{e.signal}</td>
                  <td className="num py-2 pr-3 font-medium text-destructive">{e.observed}</td>
                  <td className="num py-2 text-muted-foreground">{e.baseline}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Panel>

        <Panel title="Affected segments">
          <ul className="space-y-3">
            {incident.segments.map((s) => (
              <li key={s.segment}>
                <div className="flex items-center justify-between text-sm">
                  <span>{s.segment}</span>
                  <span className="num text-muted-foreground">
                    {s.impact}% · {s.volume.toLocaleString("en-IN")} txns
                  </span>
                </div>
                <div className="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-secondary">
                  <div
                    className="h-full rounded-full bg-primary"
                    style={{ width: `${s.impact}%` }}
                  />
                </div>
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <Panel
        title="Recommended recovery playbook"
        className="mt-4"
        action={
          <span className="num text-xs text-muted-foreground">
            Expected recovery {formatINR(expected)}
          </span>
        }
      >
        <div className="overflow-x-auto">
          <table className="w-full min-w-[860px] text-left text-sm">
            <thead>
              <tr className="border-b border-border text-[11px] uppercase tracking-wide text-muted-foreground">
                <th className="pb-2 pr-4 font-medium">Action</th>
                <th className="pb-2 pr-4 font-medium">Reason</th>
                <th className="pb-2 pr-4 font-medium">Expected recovery</th>
                <th className="pb-2 pr-4 font-medium">Policy status</th>
                <th className="pb-2 font-medium">Execution status</th>
              </tr>
            </thead>
            <tbody>
              {incident.playbook.map((a) => (
                <tr
                  key={a.id}
                  className={
                    "border-b border-border/60 align-top " +
                    (a.policyStatus === "blocked" ? "bg-destructive/6" : "")
                  }
                >
                  <td className="max-w-[240px] py-3 pr-4 font-medium">{a.action}</td>
                  <td className="max-w-[280px] py-3 pr-4 text-xs text-muted-foreground">
                    {a.reason}
                  </td>
                  <td className="num py-3 pr-4">{formatINR(a.expectedRecovery)}</td>
                  <td className="py-3 pr-4">
                    <PolicyBadge status={a.policyStatus} />
                    <p
                      className={
                        "mt-1 max-w-[240px] text-[11px] " +
                        (a.policyStatus === "blocked"
                          ? "text-destructive"
                          : "text-muted-foreground")
                      }
                    >
                      {a.policyNote}
                    </p>
                  </td>
                  <td className="py-3">
                    <ExecutionBadge status={a.executionStatus} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {blockedCount > 0 && (
          <div className="mt-4 flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-xs text-destructive">
            <ShieldAlert className="mt-0.5 size-4 shrink-0" />
            <span>
              {blockedCount} recommended action{blockedCount > 1 ? "s were" : " was"} blocked by the
              deterministic policy engine. REVIVE AI cannot override a policy verdict — a human
              finance owner must act.
            </span>
          </div>
        )}
      </Panel>

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <Panel title="Recovery result & verification">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-border text-[11px] uppercase tracking-wide text-muted-foreground">
                <th className="pb-2 font-medium">Metric</th>
                <th className="pb-2 font-medium">Before</th>
                <th className="pb-2 font-medium">After</th>
                <th className="pb-2 font-medium">Delta</th>
              </tr>
            </thead>
            <tbody>
              {incident.verification.map((v) => (
                <tr key={v.metric} className="border-b border-border/60">
                  <td className="py-2 pr-3">{v.metric}</td>
                  <td className="num py-2 pr-3 text-muted-foreground">{v.before}</td>
                  <td className="num py-2 pr-3 font-medium">{v.after}</td>
                  <td className="num py-2 font-medium text-success">{v.delta}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Panel>

        <Panel title="Audit timeline">
          <ol className="relative space-y-4 border-l border-border pl-5">
            {events.map((e) => (
              <li key={e.id} className="relative">
                <span
                  className={
                    "absolute -left-[26px] top-1.5 size-2.5 rounded-full " +
                    (e.outcome === "blocked" || e.outcome === "critical"
                      ? "bg-destructive"
                      : e.outcome === "success"
                        ? "bg-success"
                        : "bg-primary")
                  }
                />
                <div className="flex flex-wrap items-center gap-2">
                  <span className="num text-xs text-muted-foreground">{formatTime(e.at)}</span>
                  <span className="text-sm font-medium">{e.event}</span>
                  <span className="text-xs text-muted-foreground">· {e.actor}</span>
                </div>
                <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">{e.detail}</p>
              </li>
            ))}
          </ol>
        </Panel>
      </div>
    </AppShell>
  );
}
